### ISSUE TITLE
Test tlp (battery optimizer)

### ISSUE THREAD

**Issue by Its-Alex** [Its-Alex/backlog#2]
I would like to try [tlp](https://linrunner.de/tlp/introduction.html) (tool for optimizing battery on linux) on archlinux

**Comment by stephane-klein** [comment]
Est-ce que cela a un lien avec https://gitlab.com/marcosdalvarez/thinkpad-battery-threshold-extension que j'utilise 🤔

**Comment by Its-Alex** [comment]
@stephane-klein Je ne pense pas que ça ait un lien direct. C'est le même but sauf que `tpl` semble faire tout automatiquement pour optimiser

**Comment by Its-Alex** [comment]
I installed it without any problems, very easy and simple

**Comment by Its-Alex** [comment]
The CLI is simple to use with the config, I defined `charge thresholds` and I saw that a fullcharge can be done with:

```bash
$ tlp fullcharge
```

**Comment by Its-Alex** [comment]
Cons: [only a few computer can have battery optimization](https://linrunner.de/tlp/settings/bc-vendors.html)

**Comment by Its-Alex** [comment]
After about a month, I didn't see any real increase in battery performance with default setup (maybe because my current computer didn't work for batterie optimization).

**Comment by Its-Alex** [comment]
I will close this issue, maybe retry with thinkpad see if it's better

**Comment by Its-Alex** [comment]
I saw that dell use `tlp` inside their distributed ubuntu
