### ISSUE TITLE
Create a backup/restore container for postgres

### ISSUE THREAD

**Issue by Its-Alex** [Its-Alex/backlog#26]
# Context

I have some selfhosted applications and I would like to backup then using a tool like [restic](https://github.com/restic/restic). The tools must include:

- Backup from postgres
- Backup to S3
- Backup to FTP

I must know how to restore those backups. All this works will be done in a playground first.

**Comment by Its-Alex** [comment]
@stephane-klein shared https://github.com/stephane-klein/restic-pg_dump-docker with me, I would like to implement versionning before using it

**Comment by Its-Alex** [comment]
I made a PR (https://github.com/stephane-klein/restic-pg_dump-docker/pull/2), I will wait a few days see if this is merged

**Comment by stephane-klein** [comment]
> I made a PR (https://github.com/stephane-klein/restic-pg_dump-docker/pull/2), I will wait a few days see if this is merged

@Its-Alex done

**Comment by Its-Alex** [comment]
I will close and use https://github.com/stephane-klein/restic-pg_dump-docker
